[tool.poetry]
name = "trakt-scrobbler"
version = "1.3.1"
description = "Scrobbler for trakt.tv that supports VLC, Plex, MPC-HC, and MPV"
authors = ["iamkroot <kroot.patel@gmail.com>"]
readme = "README.md"
repository = "https://github.com/iamkroot/trakt-scrobbler"
license = "GPL-2.0-only"
keywords = ["trakt", "scrobbler"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
urllib3 = "^1.26.0"
guessit = "^3.3.1"
appdirs = "^1.4.4"
pywin32 = {version = ">=227", platform = "win32"}
win10toast = {version = "^0.9", platform = "win32"}
cleo = "^0.8.1"
confuse = "^1.4.0"
pysocks = {version = "^1.7.1", optional = true}
jeepney = {version = "^0.7", platform = "linux"}
urlmatch = "^1.0.1"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
socks = ["pysocks"]

[tool.poetry.scripts]
trakts = "trakt_scrobbler.console:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportGeneralTypeIssues = false
