[tool.poetry]
name = "trakt-scrobbler"
version = "1.0.0-beta.2"
description = "Scrobbler for trakt.tv that supports VLC, Plex, MPC-HC, and MPV"
authors = ["iamkroot <kroot.patel@gmail.com>"]
readme = "README.md"
repository = "https://github.com/iamkroot/trakt-scrobbler"
license = "GPL-2.0-only"
keywords = ["trakt", "scrobbler"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
guessit = "^3.1.0"
toml = "^0.10.0"
appdirs = "^1.4.3"
pywin32 = {version = "^227", platform = "win32"}
win10toast = {version = "^0.9", platform = "win32"}
cleo = "^0.7.6"
confuse = "^1.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
trakts = "trakt_scrobbler.commands:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
