[tool.poetry]
name = "trakt-scrobbler"
version = "1.2.0"
description = "Scrobbler for trakt.tv that supports VLC, Plex, MPC-HC, and MPV"
authors = ["iamkroot <kroot.patel@gmail.com>"]
readme = "README.md"
repository = "https://github.com/iamkroot/trakt-scrobbler"
license = "GPL-2.0-only"
keywords = ["trakt", "scrobbler"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
guessit = "^3.1.0"
appdirs = "^1.4.3"
pywin32 = {version = "^227", platform = "win32"}
win10toast = {version = "^0.9", platform = "win32"}
cleo = "^0.7.6"
confuse = "^1.3.0"
pysocks = {version = "^1.7.1", optional = true}
pygobject = { version = "^3.34", platform = "linux",  optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
socks = ["pysocks"]
linux_gobject = ["pygobject"]

[tool.poetry.scripts]
trakts = "trakt_scrobbler.console:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
